/**
 * songs.js
 *
 * The app's songs
 */

window.songs = [
  {
    songId: "SID-1001",
    artistId: "AID-0001",
    title: "Say So",
    year: "2020",
    duration: 236,
    url: "https://www.youtube.com/watch?v=pok8H_KF1FA",
  },
  {
    songId: "SID-2001",
    artistId: "AID-0001",
    title: "Kiss Me More (feat. SZA)",
    year: "2021",
    duration: 316,
    url: "https://www.youtube.com/watch?v=0EVVKs6DQLo",
  },
  {
    songId: "SID-3001",
    artistId: "AID-0001",
    title: "Paint the Town Red",
    year: "2023",
    duration: 295,
    url: "https://youtu.be/m4_9TFeMfJE?si=fGbn8ycLmYNJyu7a",
  },
  {
    songId: "SID-4001",
    artistId: "AID-0001",
    title: "Juicy (with Tyga)",
    year: "2019",
    duration: 198,
    url: "https://youtu.be/YIALlhlyqO4?si=HQMrRjf5IGL9EK0P",
  },
  {
    songId: "SID-5001",
    artistId: "AID-0001",
    title: "Candy",
    year: "2018",
    duration: 193,
    url: "https://youtu.be/ZRHHOttkM1A?si=MMecxfGFKv1ZbBbL",
  },
  {
    songId: "SID-1002",
    artistId: "AID-0002",
    title: "Blinding Lights",
    year: "2019",
    duration: 263,
    url: "https://www.youtube.com/watch?v=4NRXx6U8ABQ",
  },
  {
    songId: "SID-2002",
    artistId: "AID-0002",
    title: "Save Your Tears",
    year: "2021",
    duration: 249,
    url: "https://www.youtube.com/watch?v=XXYlFuWEuKI",
  },
  {
    songId: "SID-3002",
    artistId: "AID-0002",
    title: "Out of Time",
    year: "2022",
    duration: 233,
    url: "https://www.youtube.com/watch?v=2fDzCWNS3ig",
  },
  {
    songId: "SID-4002",
    artistId: "AID-0002",
    title: "Cry for Me",
    year: "2025",
    duration: 245,
    url: "https://www.youtube.com/watch?v=bn8gP5N8hqM",
  },
  {
    songId: "SID-5002",
    artistId: "AID-0002",
    title: "Wicked Games",
    year: "2012",
    duration: 281,
    url: "https://youtu.be/O1OTWCd40bc?si=ru8wJoLW87E7Lm5V",
  },
  {
    songId: "SID-1003",
    artistId: "AID-0003",
    title: "What's Next",
    year: "2021",
    duration: 200,
    url: "https://youtu.be/7EUVJaKJtBY?si=_T2hiS_WV9qeQ6aV",
  },
  {
    songId: "SID-2003",
    artistId: "AID-0003",
    title: "Nokia",
    year: "2025",
    duration: 265,
    url: "https://www.youtube.com/watch?v=8ekJMC8OtGU",
  },
  {
    songId: "SID-3003",
    artistId: "AID-0003",
    title: "Toosie Slide",
    year: "2020",
    duration: 312,
    url: "https://www.youtube.com/watch?v=xWggTb45brM",
  },
  {
    songId: "SID-4003",
    artistId: "AID-0003",
    title: "Laugh Now Cry Later (feat. Lil Durk)",
    year: "2020",
    duration: 301,
    url: "https://www.youtube.com/watch?v=JFm7YDVlqnI",
  },
  {
    songId: "SID-5003",
    artistId: "AID-0003",
    title: "Sticky",
    year: "2022",
    duration: 247,
    url: "https://www.youtube.com/watch?v=AnZcWgXZOKM",
  },
  {
    songId: "SID-1004",
    artistId: "AID-0004",
    title: "HUMBLE.",
    year: "2017",
    duration: 184,
    url: "https://www.youtube.com/watch?v=tvTRZJ-4EyI",
  },
  {
    songId: "SID-2004",
    artistId: "AID-0004",
    title: "DNA.",
    year: "2017",
    duration: 285,
    url: "https://www.youtube.com/watch?v=NLZRYQMLDW4",
  },
  {
    songId: "SID-3004",
    artistId: "AID-0004",
    title: "Alright",
    year: "2015",
    duration: 415,
    url: "https://www.youtube.com/watch?v=Z-48u_uWMHY",
  },
  {
    songId: "SID-4004",
    artistId: "AID-0004",
    title: "LOVE. (feat. Zacari)",
    year: "2017",
    duration: 222,
    url: "https://www.youtube.com/watch?v=ox7RsX1Ee34",
  },
  {
    songId: "SID-4005",
    artistId: "AID-0004",
    title: "King Kunta",
    year: "2015",
    duration: 237,
    url: "https://www.youtube.com/watch?v=hRK7PVJFbS8",
  },
  {
    songId: "SID-1005",
    artistId: "AID-0005",
    title: "a lot (feat. J. Cole)",
    year: "2018",
    duration: 392,
    url: "https://youtu.be/DmWWqogr_r8?si=VieUkohxxpbA7oTW",
  },
  {
    songId: "SID-2005",
    artistId: "AID-0005",
    title: "Bank Account",
    year: "2017",
    duration: 220,
    url: "https://youtu.be/sV2t3tW_JTQ?si=m1kyksMYXG_7aLgM",
  },
  {
    songId: "SID-3005",
    artistId: "AID-0005",
    title: "Runnin",
    year: "2020",
    duration: 205,
    url: "https://youtu.be/ZZ6VhTBcc-c?si=XvPcseKsyTqlPKlz",
  },
  {
    songId: "SID-4005",
    artistId: "AID-0005",
    title: "No Heart",
    year: "2016",
    duration: 256,
    url: "https://youtu.be/6wtwpUwxQik?si=3CD6p9QQtJ6T-2SN",
  },
  {
    songId: "SID-5005",
    artistId: "AID-0005",
    title: "Red Opps",
    year: "2016",
    duration: 167,
    url: "https://youtu.be/mWISiHcGoNg?si=yjmHTgF6vllKn5s3",
  },
];
